KutuphaneVeritabani1/KutuphaneVeritabani1/Areas/Admin/Controllers/RolYonetimController.cs
using KutuphaneVeritabani1.Areas.Admin.Models;
using KutuphaneVeritabani1.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KutuphaneVeritabani1.Areas.Admin.Controllers
{
    public class RolYonetimController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Admin/RolYonetim
        public ActionResult Index()
        {
            var RoleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(RoleStore);
          var model=  roleManager.Roles.ToList();
            return View(model);
        }
        public ActionResult RolEkle()
        {
         
            return View();
        }
        [HttpPost]
        public ActionResult RolEkle(RolEkleModel rol)
        {
            var RoleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(RoleStore);
           if( roleManager.RoleExists(rol.RolAd)==false)
            {
                roleManager.Create(new IdentityRole(rol.RolAd));
            }
            return RedirectToAction("Index");
        }
        public ActionResult RolKullaniciEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RolEkle(RolKullaniciEkleModel model)
        {
            var RoleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(RoleStore);
            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);


          var kullanici= userManager.FindByName(model.KullaniciAdi);
            userManager.AddToRole(kullanici.Id,model.RolAdi);
            if (!userManager.IsInRole(kullanici.Id,model.RolAdi))
            {
                userManager.AddToRoles(kullanici.Id, model.RolAdi);
            }
            return RedirectToAction("Index");
        }
        
    }
}

KutuphaneVeritabani1/KutuphaneVeritabani1/Areas/Admin/Views/RolYonetim/Index.cshtml
@model List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<ul>
@foreach (var item in Model)
{
    <li>@item.Name-@item.Users.Count</li>
}
</ul>
@Html.ActionLink("Yeni Rol Ekle","RolEkle")

KutuphaneVeritabani1/KutuphaneVeritabani1/Areas/Admin/Views/RolYonetim/RolEkle.cshtml
@model KutuphaneVeritabani1.Areas.Admin.Models.RolEkleModel 
@{
    ViewBag.Title = "RolEkle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>RolEkle</h2>

@using (Html.BeginForm("RolEkle","RolYonetim",FormMethod.Post))
{
@Html.TextBoxFor(m=>m.RolAd)
    <input type="submit" />
}

KutuphaneVeritabani1/KutuphaneVeritabani1/Areas/Admin/Views/RolYonetim/RolKullaniciEkle.cshtml
@model KutuphaneVeritabani1.Areas.Admin.Models.RolKullaniciEkleModel
@{
    ViewBag.Title = "RolKullaniciEkle";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>RolKullaniciEkle</h2>

@using (Html.BeginForm("RolKullaniciEkle","RolYonetim",FormMethod.Post))
{
    @Html.LabelFor(m=>m.KullaniciAdi) @Html.TextBoxFor(m=>m.KullaniciAdi)
    <br />
    @Html.LabelFor(m => m.RolAdi) @Html.TextBoxFor(m => m.RolAdi)
    <br />
    <input type="submit" />
}